# LSA training config - adapted from Sudoku config

defaults:
  - arch: trm
  - _self_

hydra:
  output_subdir: null

# Data path
data_paths: ['data/lsa-9x9-10k']
data_paths_test: []

evaluators:
  - name: lsa@LSA

# Hyperparams - Training
global_batch_size: 128

epochs: 50000
eval_interval: 5000
min_eval_interval: 0
checkpoint_every_eval: True

# Learning rates - following Sudoku example
lr: 1e-4
lr_min_ratio: 1.0
lr_warmup_steps: 2000

# Standard hyperparameter settings
beta1: 0.9
beta2: 0.95
weight_decay: 1.0
puzzle_emb_weight_decay: 1.0

# Hyperparams - Puzzle embeddings training
puzzle_emb_lr: 1e-4

seed: 0

ema: True # use Exponential-Moving-Average
ema_rate: 0.999 # EMA-rate
freeze_weights: False
